### ISSUE TITLE
Context responses for blocked movement

### ISSUE THREAD

**Issue by terracoda** [phetsims/quadrilateral#270]
We need responses for when further shape transformation or movement is blocked by
1. the shape itself
2. the bounds of the Play Area

**Comment by terracoda** [comment]
Ideas

Corners may or not be totally blocked when they hit an edge, so maybe it's best to call out the edge they have just hit, upon hitting it.
- Example edge context responses. I assume these would be preceded by an object responses.
    - At {{top}}.
    - At {{left edge}}.
    - At {{ bottom}}.
    - At {{right edge}}.
    - Could simplify:
        - Corner movement blocked by edge.
  
Corner movement can get more restricted if it is blocked by part of the shape.
- Corner movement blocked by shape.

Sides, especially long ones can get blocked more easily:
- Side movement blocked by edge.
- Side movement blocked by shape.

**Comment by terracoda** [comment]
@BLFiedler, what do you think?

**Comment by BLFiedler** [comment]
@jessegreenberg, can we call out which edge is blocking corner and/or side drag?

Fine with your last suggestion, too. Should also be accompanied by a sound to assist.

**Comment by jessegreenberg** [comment]
The model currently does not have that information, it is a single "am I within these rectangular bounds" check, not an edge collision check. It could be added as a new feature with some additional time.

**Comment by BLFiedler** [comment]
We aren't going to implement Voicing targeted to specific edges (e.g., top, bottom), but we will want Voicing and the boundary sound to fire when encounter a new edge (like when sliding along an edge you just encountered into a corner/new edge).

We talked about using the user input/vertex direction rather than the edge position to trigger the "shape blocked by edge" context response or boundary sound.

Assigning to @jessegreenberg, to spend some time on implementing this.

**Comment by jessegreenberg** [comment]
The basic context responses are in place but I couldn't get to the second (more challenging) part today.

**Comment by jessegreenberg** [comment]
OK, I think this is working as requested!

@BLFiedler can you please review the sound after this change?

@terracoda can you please review the Voicing? On thing I noticed is that the collision context responses are getting cancelled by the medium and high priority Utterances from context responses from other shape changes. Is there anything you would like to do about this?

**Comment by BLFiedler** [comment]
This sounds great from the sound side. Tested both side drag and vertex. Bounced between and along sides and heard the bonks every time I expected to. 

If the Voicing sounds good, feel free to close @terracoda

**Comment by terracoda** [comment]
Questioning some Keyboard Examples:
1. Heard "Blocked by edge" response when I hit the edge at the corner with the down arrow, but after that I hit the right arrow, and I heard "right", and no movement occurred. I expected to hear "Blocked by edge" or nothing since I was already at the two edges.
<img width="83" alt="image" src="https://user-images.githubusercontent.com/1902116/215128956-3a64a1c0-e7c0-4ddf-af0a-a8e60997e1b4.png">

2. Turned on values in case that's helpful. In this case, I heard the edge sound upon hitting the edge, and on the next key press I got the blocked response. I think this happens from time to time. And sometimes I don't hear the response. Is it possible that if the response is a little late, it gets interrupted by a key press?
<img width="709" alt="image" src="https://user-images.githubusercontent.com/1902116/215130377-f55b3f34-014d-45f4-b402-0cf02400f7e5.png">

3. In this case - moving side BC down... When Corner C hit the bottom, I heard, "Blocked by inner shape." I wasn't sure if that was the correct response? I expected to hear, "Blocked by edge."
<img width="724" alt="image" src="https://user-images.githubusercontent.com/1902116/215134090-092833e7-7cb7-45de-9941-9762c2eeeabe.png">

still testing...

**Comment by terracoda** [comment]
4. I hear both responses in this case. I hit edge and hear "Blocked by edge" response and sound, and then I hit the up arrow again and I hear the "Blocked by inner shape" response and the other blocking sound (inner shape). Should the inner shape audio (sound and speech) fire after hitting the edge? This only happens when a side hits the edge.
<img width="712" alt="image" src="https://user-images.githubusercontent.com/1902116/215136820-b77c58cd-76ff-4943-bed3-1cb448f19ea9.png">

5. Some inconsistency when a corner hits and edge. If it just so happens that the movement/step hits the edge and triggers one of the longer shape-property or shape-maintenance context responses, I think the "Blocked by edge" gets lost. Sometimes the response will fire on the next key press and sometimes it does - possibly because I have already pressed the arrow key more than once. Actually, I think this inconsistency is just some delayed responses. I played a a lot with Corner C in the scenario below and I think I heard everything I correctly, but sometimes it was a little out of synch, so it felt weird or I missed something - especially if I did multiple key presses at the edge.
<img width="716" alt="image" src="https://user-images.githubusercontent.com/1902116/215142075-61afeb91-b64a-4009-ad5b-53b9704a48b3.png">

So far, my main concern is hearing the "Blocked by inner shape" audio (sound and response) when a side or the corner of a side hits the edge. @jessegreenberg is this a bug or is there a model reason for it?

**Comment by terracoda** [comment]
The sounds work quite nicely :-)

**Comment by jessegreenberg** [comment]
OK, reviewed the list and responding to each:

1) I haven't been able to reproduce yet, will keep trying.
2) Yes, this is happening because the other context responses are higher priority than the collision context responses. 
3) I am not sure why this is happening, Ill take a look.
4) I am guessing this is caused by the same issue as 3 and as the issue @BLFiedler mentioned in https://github.com/phetsims/quadrilateral/issues/270#issuecomment-1375557197.
5) Yes, I think this is the same as 2. Context responses from shape changes are higher priority than these context responses. Would you like to try making these collision responses the same or higher priority? 

Currently changes are prioritized like this (by value):
- Shape name change: priority 10
- angle/length changed enough for shape maintenance: priority 2
- Blocked by edge/shape: priority 1
- all other context responses: priority 0

**Comment by terracoda** [comment]
@jessegreenberg and @terracoda discussed the priority of each response.

We'll try upping the priority of Blocked by edge/shape to 2, so the it has the same priority as shape maintenance, and I'll see how that goes.

**Comment by jessegreenberg** [comment]
OK, coming back to this issue after a siesta. The remaining work is
- [ ] @BLFiedler noted a bug with the collision detection in https://github.com/phetsims/quadrilateral/issues/270#issuecomment-1375557197.
- [ ] @terracoda would like to try a change to the `priority` value of blocked responses in https://github.com/phetsims/quadrilateral/issues/270#issuecomment-1409407387.

**Comment by jessegreenberg** [comment]
Alright, these were fixed in the above commit. 

- @BLFiedler can you please verify that https://github.com/phetsims/quadrilateral/issues/270#issuecomment-1375557197 is fixed?
- @terracoda can you please try out the context responses for blocked shapes?

**Comment by jessegreenberg** [comment]
We discussed today that @terracoda will review but this doesn't need to block the next test.

**Comment by terracoda** [comment]
Hmm, I feel like these responses are working well together.

I do still get a shape maintenance response sometimes when hitting the edge, rather than an edge response.
I think this happens when the threshold for a shape maintenance/shape area change triggers right at the edge.

Wiggling around mixes things up, so I feel like a person can get themselves out of a restricted spot.

I am willing to leave things as-is. I think we already changed the priority of the edge response, to be greater than the shape-maintenance response, so I feel edge responses are happening more than before, and the occasional shape-maintenance response that happens at the edge can be tolerated in a useful way since the response does provide information about the actual shape.
